FROM nginx
USER root
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./miniserver.c /home/miniserver.c
COPY ./entrypoint.sh /home/entrypoint.sh
RUN apt-get update; \
    apt-get install -y gcc spawn-fcgi libfcgi-dev; \
    chmod 777 /home/entrypoint.sh
WORKDIR /home/
CMD ["/home/entrypoint.sh"]
